export const modules = [
  {
    id:'glucose', title:'糖代谢与胰岛', en:'GLUCOSE HOMEOSTASIS', short:'糖代谢', icon:'◈', color:'#55d5c5', duration:240, unit:'分钟', step:0.25,
    subtitle:'跟随一餐之后的葡萄糖，理解分泌、摄取与反馈。',
    question:'相同的一餐，为什么会出现不同的血糖曲线？',
    tags:['胰岛 β 细胞','胰岛素抵抗','肝糖输出'],
    metrics:[['g','血糖','#55d5c5'],['i','胰岛素','#b998f4'],['u','外周摄糖','#78aefb'],['h','肝糖输出','#f6b56d']],
    scenarios:[{id:'normal',name:'正常调节',desc:'分泌与外周响应完整',params:{sensitivity:1,capacity:1}},{id:'resistance',name:'胰岛素抵抗',desc:'外周及肝脏响应减弱',params:{sensitivity:0.35,capacity:1}},{id:'deficiency',name:'分泌功能减弱',desc:'β 细胞响应能力下降',params:{sensitivity:1,capacity:0.3}}],
    experiment:'恢复胰岛素响应', experimentNote:'将模型中的胰岛素敏感性恢复至基准，并保留分支点前的全部状态。这是机制实验，不代表某种药物。',
    nodes:[['gut','消化道',-3.4,1.6,0,'g'],['glucose','血液葡萄糖',0,1.8,0,'g'],['beta','胰岛 β 细胞',3.4,1.2,0,'i'],['insulin','胰岛素',2.5,-1.5,0.3,'i'],['muscle','肌肉与脂肪',-0.7,-2,0,'u'],['liver','肝脏',-3.5,-1.2,0,'h']],
    edges:[['gut','glucose','+'],['glucose','beta','+'],['beta','insulin','+'],['insulin','muscle','+'],['muscle','glucose','−'],['insulin','liver','−'],['liver','glucose','+']],
    focus:'muscle', explain:'餐后葡萄糖进入循环，促使 β 细胞分泌胰岛素。胰岛素促进肌肉和脂肪组织摄糖，并抑制肝糖输出；这些作用共同改变血糖的变化速度。',
    misconception:'GLUT4 主要用于展示肌肉与脂肪组织的胰岛素敏感性转运。肝脏通过糖代谢及糖输出参与调节，不能沿用同一套 GLUT4 动画。胰岛素进入血管，不经过胰管。',
    quiz:{q:'胰岛素抵抗时，哪一项最能解释餐后血糖回落变慢？',answers:['外周摄糖与肝糖输出抑制均可能受影响','葡萄糖只通过胰管进入血液','胰岛素越多就一定回落越快'],correct:0,reason:'胰岛素浓度和组织对胰岛素的响应是两个不同变量。需要同时观察分泌、外周摄糖与肝糖输出。'},
    sources:[['葡萄糖与胰岛素餐后模型','https://pubmed.ncbi.nlm.nih.gov/17926672/'],['葡萄糖转运与稳态','https://www.jci.org/articles/view/29027'],['胰腺内外分泌功能','https://www.niddk.nih.gov/-/media/Files/Strategic-Plans/2020_NIDDK_RecentAdvancesEmergingOpps_DEM.pdf']],
  },
  {
    id:'thyroid', title:'甲状腺调节轴', en:'HYPOTHALAMIC–PITUITARY–THYROID AXIS', short:'甲状腺', icon:'⋈', color:'#b998f4', duration:14, unit:'天', step:0.025,
    subtitle:'沿着 TRH、TSH 与甲状腺激素，定位反馈失衡的位置。', question:'甲状腺激素偏低时，TSH 为什么可能升高，也可能偏低？', tags:['HPT 轴','负反馈','原发与中枢'],
    metrics:[['g','甲状腺激素','#b998f4'],['p','TSH','#55d5c5'],['h','TRH 信号','#78aefb']],
    scenarios:[{id:'normal',name:'正常反馈',desc:'调节轴维持平衡',params:{capacity:1,pituitary:1}},{id:'primary',name:'原发性功能减弱',desc:'甲状腺响应下降',params:{capacity:0.3,pituitary:1}},{id:'central',name:'中枢驱动减弱',desc:'垂体驱动下降',params:{capacity:1,pituitary:0.3}}],
    experiment:'恢复甲状腺响应',experimentNote:'只恢复甲状腺响应参数，观察反馈是否足以恢复平衡；中枢驱动不足时，这一变化可能不足以恢复输出。',
    nodes:[['hypothalamus','下丘脑',0,2.4,0,'h'],['pituitary','垂体',0,0.3,0,'p'],['thyroid','甲状腺',0,-2,0,'g'],['tissue','靶组织',3.6,-1.5,0,'g']],edges:[['hypothalamus','pituitary','+'],['pituitary','thyroid','+'],['thyroid','hypothalamus','−'],['thyroid','pituitary','−'],['thyroid','tissue','+']],
    focus:'pituitary',explain:'下丘脑与垂体向甲状腺传递促分泌信号。甲状腺激素对上游形成负反馈，因此必须结合 TSH 与甲状腺激素判断失衡位置。',
    misconception:'低甲状腺激素并不总伴随高 TSH。中枢性病变可能使 TSH 偏低或不恰当地正常。本模型合并显示甲状腺激素，不区分 T3 与 T4 的药代过程。',
    quiz:{q:'甲状腺输出降低且 TSH 也偏低，更值得定位哪一级？',answers:['只考虑外周组织','下丘脑或垂体的中枢驱动','一定是碘摄入不足'],correct:1,reason:'完整的上游系统会对低激素产生反馈性反应；不恰当的低 TSH 提示需要考虑中枢层级。'},sources:[['甲状腺功能减退','https://www.niddk.nih.gov/health-information/endocrine-diseases/hypothyroidism']],
  },
  {
    id:'adrenal',title:'肾上腺与应激',en:'HYPOTHALAMIC–PITUITARY–ADRENAL AXIS',short:'肾上腺',icon:'△',color:'#f6b56d',duration:24,unit:'小时',step:0.04,
    subtitle:'把昼夜节律与应激放在同一条时间轴上。',question:'一次应激之后，皮质醇和 ACTH 如何相互影响？',tags:['HPA 轴','皮质醇','昼夜节律'],
    metrics:[['g','皮质醇','#f6b56d'],['p','ACTH','#b998f4'],['h','CRH 信号','#55d5c5']],
    scenarios:[{id:'normal',name:'完整应激响应',desc:'节律与应激共同驱动',params:{capacity:1,pituitary:1}},{id:'primary',name:'肾上腺功能减弱',desc:'皮质醇合成响应下降',params:{capacity:0.3,pituitary:1}},{id:'central',name:'ACTH 驱动减弱',desc:'垂体刺激不足',params:{capacity:1,pituitary:0.3}}],
    experiment:'恢复肾上腺响应',experimentNote:'恢复肾上腺响应能力，比较相同应激下的激素变化。此处只模拟糖皮质激素轴。',
    nodes:[['hypothalamus','下丘脑',0,2.4,0,'h'],['pituitary','垂体 ACTH',0,0.2,0,'p'],['adrenal','肾上腺皮质',0,-2,0,'g'],['stress','应激输入',-3.5,1.6,0,'h'],['tissue','靶组织',3.5,-1.5,0,'g']],edges:[['stress','hypothalamus','+'],['hypothalamus','pituitary','+'],['pituitary','adrenal','+'],['adrenal','pituitary','−'],['adrenal','hypothalamus','−'],['adrenal','tissue','+']],
    focus:'adrenal',explain:'应激可增强 HPA 轴驱动，ACTH 促进皮质醇分泌，皮质醇又反馈抑制上游。判断变化时应同时考虑分泌节律和取样时间。',misconception:'单个时间点不能代表整日激素水平。本场景不覆盖醛固酮、儿茶酚胺或急性肾上腺危象的治疗。',
    quiz:{q:'相同应激下，皮质醇偏低且 ACTH 升高，机制上更符合哪种情况？',answers:['肾上腺本身响应减弱','一定是垂体完全停止分泌','ACTH 对皮质醇没有影响'],correct:0,reason:'肾上腺输出不足削弱负反馈，上游 ACTH 可代偿性升高。'},sources:[['肾上腺功能不全','https://www.niddk.nih.gov/health-information/endocrine-diseases/adrenal-insufficiency-addisons-disease']],
  },
  {
    id:'gonadal',title:'性腺调节轴',en:'HYPOTHALAMIC–PITUITARY–GONADAL AXIS',short:'性腺轴',icon:'⌘',color:'#ed8ead',duration:14,unit:'天',step:0.025,
    subtitle:'以睾酮反馈为入口，理解中枢与性腺的双向调节。',question:'激素输出下降，如何区分性腺与上游驱动问题？',tags:['HPG 轴','LH','负反馈定位'],
    metrics:[['g','睾酮','#ed8ead'],['p','LH','#b998f4'],['h','GnRH 信号','#55d5c5']],
    scenarios:[{id:'normal',name:'正常反馈',desc:'平均分泌信号平衡',params:{capacity:1,pituitary:1}},{id:'primary',name:'性腺响应减弱',desc:'末端合成能力下降',params:{capacity:0.3,pituitary:1}},{id:'central',name:'中枢驱动减弱',desc:'促性腺激素驱动不足',params:{capacity:1,pituitary:0.3}}],
    experiment:'恢复性腺响应',experimentNote:'只恢复性腺响应，保留上游状态，区分原发性与中枢性失衡。',
    nodes:[['hypothalamus','下丘脑 GnRH',0,2.4,0,'h'],['pituitary','垂体 LH',0,0.2,0,'p'],['gonad','睾丸',0,-2,0,'g'],['tissue','雄激素靶组织',3.5,-1.4,0,'g']],edges:[['hypothalamus','pituitary','+'],['pituitary','gonad','+'],['gonad','hypothalamus','−'],['gonad','pituitary','−'],['gonad','tissue','+']],
    focus:'pituitary',explain:'GnRH 促进垂体释放促性腺激素，LH 促进睾酮生成。睾酮及其代谢相关信号对上游形成反馈，使末端输出与中枢驱动相互关联。',misconception:'这里显示男性轴的平均分泌信号。GnRH 脉冲、FSH 与抑制素、卵巢周期和雌激素正反馈需要独立扩展模型。',
    quiz:{q:'睾酮降低同时 LH 升高，最直接提示哪一层反馈失衡？',answers:['所有层级都正常','原发性性腺响应不足','GnRH 脉冲完全消失'],correct:1,reason:'末端输出降低可解除负反馈，使 LH 升高；中枢驱动不足时通常不会出现这种恰当代偿。'},sources:[['下丘脑垂体睾丸轴的调节','https://pubmed.ncbi.nlm.nih.gov/35216719/'],['雄激素生理','https://ncbi.nlm.nih.gov/books/NBK279000/?report=reader']],
  },
  {
    id:'calcium',title:'钙磷与骨代谢',en:'CALCIUM AND BONE HOMEOSTASIS',short:'钙磷骨代谢',icon:'◇',color:'#83baf8',duration:48,unit:'小时',step:0.08,
    subtitle:'连接甲状旁腺、肾脏与骨，追踪钙反馈回路。',question:'PTH 的改变，为什么会同时牵动血钙和血磷？',tags:['PTH','骨肾耦合','血钙反馈'],
    metrics:[['g','血钙','#83baf8'],['p','PTH','#b998f4'],['h','血磷','#f6b56d'],['u','钙动员信号','#55d5c5']],
    scenarios:[{id:'normal',name:'正常反馈',desc:'感知血钙并调节 PTH',params:{autonomous:0,capacity:1}},{id:'hyper',name:'PTH 自主分泌',desc:'加入独立分泌信号',params:{autonomous:1.3,capacity:1}},{id:'hypo',name:'PTH 分泌不足',desc:'甲状旁腺响应减弱',params:{autonomous:0,capacity:0.25}}],
    experiment:'恢复 PTH 调节',experimentNote:'恢复甲状旁腺的基准响应与反馈耦合，比较血钙、血磷方向变化。本实验假设肾功能正常。',
    nodes:[['calcium','循环血钙',0,2.3,0,'g'],['parathyroid','甲状旁腺',0,0,0,'p'],['bone','骨组织',-3.3,-1.8,0,'u'],['kidney','肾脏',3.3,-1.8,0,'h']],edges:[['calcium','parathyroid','−'],['parathyroid','bone','+'],['parathyroid','kidney','+'],['bone','calcium','+'],['kidney','calcium','+']],
    focus:'parathyroid',explain:'血钙反馈调节 PTH。PTH 通过骨和肾等环节维持钙稳态，并促进肾脏排磷，因此血钙和血磷可能向不同方向变化。',misconception:'血磷响应受肾功能等因素影响。本模型不适用于慢性肾病相关矿物质骨代谢异常，也不模拟维生素 D 与 FGF23 的完整网络。',
    quiz:{q:'在肾功能正常的假设下，PTH 持续增高可推动哪一组变化？',answers:['血钙降低且血磷必然升高','血钙与血磷完全不受影响','血钙升高并促进排磷'],correct:2,reason:'PTH 的骨和肾作用共同影响血钙；对肾磷重吸收的影响可促进排磷。'},sources:[['原发性甲状旁腺功能亢进','https://www.niddk.nih.gov/health-information/endocrine-diseases/primary-hyperparathyroidism']],
  },
  {
    id:'energy',title:'肥胖与能量代谢',en:'ENERGY BALANCE AND ADIPOSE SIGNALING',short:'能量代谢',icon:'◉',color:'#e9c776',duration:28,unit:'天',step:0.05,
    subtitle:'从能量输入、消耗与脂肪信号理解长期动态。',question:'同样的能量输入，反馈响应不同会带来什么变化？',tags:['能量平衡','脂肪信号','食欲反馈'],
    metrics:[['g','能量储存','#e9c776'],['p','脂肪反馈信号','#b998f4'],['h','摄入驱动','#55d5c5'],['u','消耗水平','#83baf8']],
    scenarios:[{id:'normal',name:'能量平衡',desc:'输入与消耗平衡',params:{excess:0,response:1}},{id:'surplus',name:'持续能量盈余',desc:'提高外源能量输入',params:{excess:0.3,response:1}},{id:'resistance',name:'反馈响应减弱',desc:'相同盈余下的弱反馈',params:{excess:0.3,response:0.2}}],
    experiment:'恢复能量输入',experimentNote:'将外源能量输入恢复至基准，保留已累积的储存状态与反馈滞后。相对储存量不能换算为体重。',
    nodes:[['intake','能量输入',-3.4,1.5,0,'h'],['brain','中枢食欲调节',0,2,0,'h'],['adipose','脂肪与能量储存',0,-1.5,0,'g'],['signal','脂肪反馈信号',3.4,1,0,'p'],['expenditure','能量消耗',-3.3,-1.8,0,'u']],edges:[['brain','intake','+'],['intake','adipose','+'],['adipose','signal','+'],['signal','brain','−'],['adipose','expenditure','+'],['expenditure','adipose','−']],
    focus:'brain',explain:'能量储存由输入与消耗的差额推动，脂肪相关信号参与食欲及能量调节。响应强度和反馈滞后影响长期轨迹。',misconception:'肥胖受到生物、环境、药物和行为等多重因素影响。这里的聚合信号用于学习反馈，不等同于测得的瘦素浓度，也不预测个人体重。',
    quiz:{q:'能量输入恢复基准后，储存量为什么不会立刻回到起点？',answers:['已经累积的状态和反馈都有时间过程','能量守恒已经失效','脂肪信号会瞬间清除全部储存'],correct:0,reason:'储存量是长期积分形成的状态。调整输入改变后续的变化速度，而不是抹去过去的累积。'},sources:[['影响体重与健康的因素','https://www.niddk.nih.gov/health-information/weight-management/adult-overweight-obesity/factors-affecting-weight-health']],
  },
];
export const getModule = id => modules.find(m=>m.id===id) ?? modules[0];
